[package]
name = "rusn_dos"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["env", "derive"] }
env_logger = "0.11.10"
log = { version = "0.4.29", features = [ "std"] }
serde = { version = "1.0.228", features = ["derive", "serde_derive"] }
serde_json = "1.0.149"
toml = "1.1.2+spec-1.1.0"
dos_core = { path = "libs/dos_core"}
minifb = "0.28.0"
config = "0.15.22"

[workspace]
members = ['libs/*']
resolver = "2"
