title = "Biing!"
[resolution]
width = 1024
height = 768

[[drivers]]
letter = "C"
path = "./test"      # Локальный путь для диска C:
read_only = false

[[drivers]]
letter = "Z"
path = "/tmp/mgk/"   # Локальный путь для диска Z:
read_only = true     # Защита от записи