title = "Biing!"
[resolution]
width = 1024
height = 768

[[drivers]]
letter = "C"
path = "./app"
read_only = false

[[drivers]]
letter = "Z"
path = "/tmp/mgk/"
read_only = true

[[cpus]]
name = "486"
type = "x86"
feature = ["486", "mmx"]

[[cpus]]
name = "x86"
type = "x86"
feature = ["default"]
